---
- hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Upgrade everything 
      apt:
        name: "*"
        state: latest
        force_apt_get: True

    - name: Install packages
      ansible.builtin.package:
        name:  
          - build-essential
          - git
          - curl
          - python3
          - pip
        state: present             
    - name: Install serial python package
      ansible.builtin.pip:
        name: pyserial
    - name: Install Arduino-CLI
      shell:
        "curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh"
    
    - name: setup arduino-cli
      shell:
        "./startup.sh"

        # Need to start snapd service and snap refresh before installing the arduino cli