---
- hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Upgrade everything 
      apt:
        name: "*"
        state: latest
        force_apt_get: True

    - name: Install packages
      ansible.builtin.package:
        name:  
          - build-essential
          - git
        state: present             

    - name: Install Arduino-CLI
      community.general.snap:
        name:
          - arduino-cli
        state: present             
    
    - name: setup arduino-cli
      shell:
        "./startup.sh"